spring.application.name=toramie store manager
# PostgreSQL Local Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/toramie_store_manager_db
spring.datasource.username=postgres
spring.datasource.password=damian
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA / Hibernate Settings
#creates/updates tables automatically
spring.jpa.hibernate.ddl-auto=update
#shows SQL queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Static Credential
spring.security.user.name=admin
spring.security.user.password=12345